name: ci


on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Awarnings
  RUST_BACKTRACE: 1
  # Change to specific Rust release to pin
  rust_version: '1.76'


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust v${{ env.rust_version }}
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt clippy

    - name: Cache
      uses: Swatinem/rust-cache@v2

    - name: Run clippy
      run: cargo clippy --all --tests --all-features --no-deps

    - name: Format
      uses: mbrobbel/rustfmt-check@master
      with:
        token: ${{ secrets.RUSTFMT_GITHUB_TOKEN }}





